name: Publish @morrf/types

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bump patch version (if no manual bump)
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if git diff HEAD^ HEAD -- package.json | grep -q '"version":'; then
            echo "Manual version bump detected. Skipping patch bump."
          else
            echo "Auto bumping patch version..."
            npm version patch --no-git-tag-version
          fi

      - name: Build
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Create GitHub Release Zip
        run: |
          VERSION=$(node -p "require('./package.json').version")
          ZIP_NAME="types-v$VERSION.zip"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: release v$VERSION"
          git tag "v$VERSION"
          git push origin main --tags
          zip -r $ZIP_NAME dist/

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          files: types-v*.zip
